INSERT INTO health_tips (category, tip) VALUES
-- Water
('Water', 'Keep a water bottle nearby throughout the day to remind yourself to sip.'),
('Water', 'Sip water regularly instead of waiting until you feel thirsty.'),
('Water', 'Herbal teas and infused water can make hydration more enjoyable.'),
('Water', 'Soups, fruits, and veggies also contribute to hydration.'),
('Water', 'Drinking water before and after activity helps replace what’s lost.'),
('Water', 'Hydration supports focus, mood, and energy.'),
('Water', 'Add lemon, cucumber, or fruit slices if plain water feels boring.'),
-- Sleep
('Sleep', 'A consistent bedtime and wake-up time even on weekends can improve sleep quality.'),
('Sleep', 'A cool, dark, and quiet room helps you fall asleep faster.'),
('Sleep', 'Put your phone down 30 minutes before bed to let your mind unwind.'),
('Sleep', 'Sleep routines, like reading or gentle stretches, prepare your body for rest.'),
('Sleep', 'Create a calming routine before bed (dim lights, quiet activity).'),
('Sleep', 'Quality sleep supports memory, focus, mood, immune health, and emotional well-being.'),
('Sleep', 'Even short disruptions in sleep can affect your mood and energy.'),
('Sleep', 'If you can’t sleep, get up and do something calming until you feel sleepy again.'),
-- Naps
('Naps', 'Short naps (15–30 minutes) can recharge focus and energy.'),
('Naps', 'Naps are not laziness—your body may truly need the reset.'),
('Naps', 'Avoid napping too late in the day if it interferes with night sleep.'),
('Naps', 'A quiet, comfortable spot helps naps feel restorative.'),
('Naps', 'Resting with your eyes closed, even if you don’t fall asleep, can still be restorative.'),
-- Exercise & Movement
('Exercise & Movement', 'Movement doesn’t have to mean the gym—walking, dancing, stretching all count.'),
('Exercise & Movement', 'A mix of strength, cardio, and flexibility training helps overall fitness.'),
('Exercise & Movement', 'Mix different types of movement to keep things fresh and balanced.'),
('Exercise & Movement', 'Take short breaks to stretch or walk if you’ve been sitting a long time.'),
('Exercise & Movement', 'Exercise can support mental health as much as physical health.'),
('Exercise & Movement', 'Consistent movement boosts mood and lowers stress.'),
('Exercise & Movement', 'Consistency often matters more than intensity.'),
('Exercise & Movement', 'Pick activities you enjoy so exercise feels like play, not punishment.'),
('Exercise & Movement', 'Warm-ups and cooldowns help reduce the risk of injury.'),
('Exercise & Movement', 'Strength training builds resilience in bones and joints.'),
('Exercise & Movement', 'Cardio supports heart and lung health.'),
('Exercise & Movement', 'Listen to your body—push when you feel strong, rest when you feel drained.'),
-- Rest & Recovery
('Rest & Recovery', 'Muscles grow and repair during rest, not during the workout itself.'),
('Rest & Recovery', 'Rest days are just as important as workout days.'),
('Rest & Recovery', 'Overtraining can lead to fatigue or burnout—balance is key.'),
('Rest & Recovery', 'Gentle movement like yoga or walking can aid active recovery.'),
('Rest & Recovery', 'Listening to your body’s signals helps prevent pushing too hard.'),
('Rest & Recovery', 'Give yourself permission to take a full rest day when needed.'),
('Rest & Recovery', 'Relaxation practices like meditation can recharge energy.'),
('Rest & Recovery', 'Quality rest prevents burnout and helps keep habits sustainable.'),
-- Electrolytes
('Electrolytes', 'Electrolytes help regulate hydration and muscle function.'),
('Electrolytes', 'Along with water, your body needs electrolytes (sodium, potassium, magnesium) for balance.'),
('Electrolytes', 'Sweating a lot? A pinch of salt or an electrolyte drink can help replenish.'),
('Electrolytes', 'Foods like bananas, leafy greens, and yogurt can provide electrolytes.'),
('Electrolytes', 'Fruits, veggies, and a varied diet provide natural electrolytes.'),
('Electrolytes', 'Coconut water and electrolyte drinks are options after intense activity.'),
('Electrolytes', 'Balanced nutrition usually supports healthy electrolyte levels.'),
('Electrolytes', 'Signs of imbalance can include headaches, muscle cramps, or fatigue.'),
-- Sunlight
('Sunlight', 'Morning sunlight helps regulate your body’s sleep-wake cycle.'),
('Sunlight', 'A few minutes of sunlight daily can boost mood, alertness, and vitamin D.'),
('Sunlight', 'Morning light exposure may help you feel more awake.'),
('Sunlight', 'Spending time outdoors supports mental health, lowers stress, and overall well-being.'),
('Sunlight', 'Indoor plants or even looking at greenery can have calming effects.'),
-- Balance
('Balance', 'Balancing activity with downtime helps avoid burnout.'),
('Balance', 'Exercise and recovery work together for progress.'),
('Balance', 'Too little rest can hold back performance and motivation.'),
('Balance', 'Gentle activities on off days can still support movement goals.'),
-- Food & Nourishment
('Food & Nourishment', 'Aim to include protein, carbs, and veggies throughout the day.'),
('Food & Nourishment', 'Eat a variety of colors—different foods give different nutrients.'),
('Food & Nourishment', 'Comfort foods have value too—they support emotional well-being.'),
('Food & Nourishment', 'Slow down while eating to enjoy the flavors and notice fullness.'),
('Food & Nourishment', 'Snacks can be part of a healthy rhythm—don’t ignore hunger cues.'),
('Food & Nourishment', 'Cooking at home, even simple meals, helps you connect with your food.'),
('Food & Nourishment', 'Sharing meals with others can be good for social and mental health.'),
('Food & Nourishment', 'Balance matters more than perfection—every food has a place.'),
-- General Wellness
('General Wellness', 'Mental health is just as important as physical health.'),
('General Wellness', 'Taking breaks during work helps maintain focus.'),
('General Wellness', 'Deep breathing supports calm and reduces tension.'),
('General Wellness', 'Stress management is part of health—deep breathing, journaling, or hobbies can help.'),
('General Wellness', 'Nature walks can help reduce stress.'),
('General Wellness', 'Staying connected with friends and loved ones supports resilience.'),
('General Wellness', 'Laughter and play are healthy too—they reduce stress hormones.'),
('General Wellness', 'Keeping a regular routine can support both body and mind.'),
('General Wellness', 'Gratitude practices can shift focus toward what’s working well.'),
('General Wellness', 'Small daily habits often make the biggest difference long term.'),
('General Wellness', 'Break big goals into small, doable steps—it reduces overwhelm.'),
('General Wellness', 'Listening to your body’s needs is an important skill.'),
('General Wellness', 'Self-care is not indulgent—it’s maintenance.'),
('General Wellness', 'Balance across work, rest, movement, and fun supports a healthy lifestyle.'),
('General Wellness', 'Celebrate progress, no matter how small.');