INSERT INTO affirmations (message) VALUES
('You are enough, just as you are.'),
('Small steps are still steps forward.'),
('Resting is part of growth.'),
('Your efforts matter, even when they feel small.'),
('It’s okay to move at your own pace.'),
('You deserve kindness—especially from yourself.'),
('Taking care of yourself is a beautiful thing.'),
('You don’t have to do everything today.'),
('Balance matters more than perfection.'),
('You’re allowed to take up space.'),
('Progress is built one moment at a time.'),
('Self-care is not selfish—it’s necessary.'),
('Your well-being is worth tending to.'),
('Breathe. You’re safe in this moment.'),
('Every day is a fresh start.'),
('Listening to your body is an act of respect.'),
('You’re learning to care for yourself in new ways.'),
('Joy can be found in small, ordinary moments.'),
('You are stronger than you think.'),
('Patience with yourself is a form of kindness.'),
('You don’t need to earn rest—it’s already yours.'),
('Even gentle effort is valuable.'),
('Every breath is a reminder of life’s rhythm.'),
('You are allowed to grow and change.'),
('Your presence has value.'),
('You’re doing better than you realize.'),
('It’s okay to need support sometimes.'),
('Your journey is uniquely yours.'),
('Take pride in how far you’ve already come.'),
('Peace can be found in slowing down.');
